# Generated by Django 5.0.14 on 2026-05-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fda_notice',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
